### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 532910** [jspricke/radicale-storage#15]
```
% radicale --version
2.1.11
```

with radicale-remind from git:
```
% radicale -f -D
[7f2c66361740] INFO: Starting Radicale
[7f2c66361740] INFO: Authentication type is 'htpasswd'
[7f2c66361740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 107, in load
    collection_class = import_module(storage_type).Collection
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/radicale_remind-0.2.5-py3.7.egg/radicale_remind.py", line 25, in <module>
    from radicale.item import Item
ModuleNotFoundError: No module named 'radicale.item'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 110, in load
    (storage_type, e)) from e
RuntimeError: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
```

with https://github.com/jspricke/radicale-remind/archive/v0.2.5.tar.gz
```
% radicale -f -D
[7f8e4196f740] INFO: Starting Radicale
[7f8e4196f740] INFO: Authentication type is 'htpasswd'
[7f8e4196f740] INFO: Storage type is 'radicale_remind'
[7f8e4196f740] ERROR: An exception occurred during server startup: static_init() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 117, in load
    CollectionCopy.static_init()
TypeError: static_init() takes 0 positional arguments but 1 was given
```

**Comment by jspricke** [comment]
Do you have python-remind installed? How did you install the python packages?

**Comment by 532910** [comment]
sure!

**Comment by jspricke** [comment]
radicale-remind git master should work with Radicale git master. radicale-remind 0.2.5 should work with Radicale 2.1.9. Radicale broke some APIs, so I only adopted to the new Radicale master..

**Comment by 532910** [comment]
```
# debootstrap sid sid http://deb.debian.org/debian
# chroot sid
# apt update
# apt install python3-pip
# pip3 install radicale-remind
# radicale -f -C /tmp/config 
[7f4b41fa4740] INFO: Starting Radicale
[7f4b41fa4740] INFO: Authentication type is 'htpasswd'
[7f4b41fa4740] INFO: Storage type is 'radicale_remind'
[7f4b41fa4740] ERROR: An exception occurred during server startup: static_init() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/radicale/storage.py", line 117, in load
    CollectionCopy.static_init()
TypeError: static_init() takes 0 positional arguments but 1 was given
```

```
# debootstrap sid sid http://deb.debian.org/debian
# chroot sid
# apt update
# apt install git python3-setuptools
# git clone https://github.com/jspricke/radicale-remind
# cd radicale-remind
# python3 setup.py install
# radicale -f -C /tmp/config 
[7f4fd4353740] INFO: Starting Radicale
[7f4fd4353740] INFO: Authentication type is 'htpasswd'
[7f4fd4353740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/storage.py", line 107, in load
    collection_class = import_module(storage_type).Collection
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/radicale_remind-0.2.5-py3.7.egg/radicale_remind.py", line 25, in <module>
    from radicale.item import Item
ModuleNotFoundError: No module named 'radicale.item'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/storage.py", line 110, in load
    (storage_type, e)) from e
RuntimeError: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
```

**Comment by jspricke** [comment]
you are using the pip version of Radicale (i.e. 2.1.11). As written above, you would need the _git_ version: https://github.com/Kozea/Radicale

**Comment by 532910** [comment]
> you are using the pip version of Radicale (i.e. 2.1.11). As written above, you would need the _git_ version: https://github.com/Kozea/Radicale

have you read the second example?

**Comment by jspricke** [comment]
Yes, this still installs the pip version of Radicale. You would need to git clone and install Radicale manually.

**Comment by c-e-p-x-u-o** [comment]
Just a copy paste.

**Comment by c-e-p-x-u-o** [comment]
```
# debootstrap sid sid http://deb.debian.org/debian
# chroot sid
# apt update
# apt install git python3-setuptools
# git clone https://github.com/jspricke/radicale-remind
# cd radicale-remind
# python3 setup.py install
# radicale -f -C /tmp/config 
[7f4fd4353740] INFO: Starting Radicale
[7f4fd4353740] INFO: Authentication type is 'htpasswd'
[7f4fd4353740] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/storage.py", line 107, in load
    collection_class = import_module(storage_type).Collection
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/radicale_remind-0.2.5-py3.7.egg/radicale_remind.py", line 25, in <module>
    from radicale.item import Item
ModuleNotFoundError: No module named 'radicale.item'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/local/lib/python3.7/dist-packages/Radicale-2.1.11-py3.7.egg/radicale/storage.py", line 110, in load
    (storage_type, e)) from e
RuntimeError: Failed to load storage module 'radicale_remind': No module named 'radicale.item'
```

**Comment by 532910** [comment]
you'd like to say ```python3 setup.py install``` installs pip version of Radicale ?

**Comment by jspricke** [comment]
Yes.
Do something like:
```
# debootstrap sid sid http://deb.debian.org/debian
# chroot sid
# apt update
# apt install git python3-setuptools
# git clone https://github.com/Kozea/Radicale
# cd radicale
# python3 setup.py install
# cd ..
# git clone https://github.com/jspricke/radicale-remind
# cd radicale-remind
# python3 setup.py install
```

**Comment by 532910** [comment]
OK, git version works together. Could you add radicale version dependency.

**Comment by jspricke** [comment]
Yes, once the is a new Radicale version.

**Comment by 532910** [comment]
You already can add  Radicale>2.1.11
