### ISSUE TITLE
NotImplementedError when creating calendars from Radicale

### ISSUE THREAD

**Issue by gour** [jspricke/radicale-storage#23]
Hello,

when I try to create a new collection (calendar) from within Radicale's admin I get the following:

```
Jul 07 19:17:18 s30.wservices.ch env[3260193]: Traceback (most recent call last):
Jul 07 19:17:18 s30.wservices.ch env[3260193]:   File "/home/atmarama/.local/lib/python3.9/site-packages/radicale/app/__init__.py", line 105, in __call__
Jul 07 19:17:18 s30.wservices.ch env[3260193]:     status_text, headers, answers = self._handle_request(environ)
Jul 07 19:17:18 s30.wservices.ch env[3260193]:   File "/home/atmarama/.local/lib/python3.9/site-packages/radicale/app/__init__.py", line 287, in _handle_request
Jul 07 19:17:18 s30.wservices.ch env[3260193]:     status, headers, answer = function(
Jul 07 19:17:18 s30.wservices.ch env[3260193]:   File "/home/atmarama/.local/lib/python3.9/site-packages/radicale/app/mkcol.py", line 71, in do_MKCOL
Jul 07 19:17:18 s30.wservices.ch env[3260193]:     self._storage.create_collection(path, props=props)
Jul 07 19:17:18 s30.wservices.ch env[3260193]:   File "/home/atmarama/.local/lib/python3.9/site-packages/radicale/storage/__init__.py", line 336, in create_collection
Jul 07 19:17:18 s30.wservices.ch env[3260193]:     raise NotImplementedError
Jul 07 19:17:18 s30.wservices.ch env[3260193]: NotImplementedError
```

Do I miss something or should I create new *.rem file for  the calendar first with Remind?

**Comment by jspricke** [comment]
>should I create new *.rem file for the calendar first with Remind

This. Creating new calendars from Radicale is not implemented due to security concerns (and no one asked till now :D )
